# Generated by Django 4.2.6 on 2025-03-04 18:37

from django.db import migrations, models
import proyecto_ips_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_ips_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=proyecto_ips_app.models.user_directory_path, verbose_name='Imagen de Usuario'),
        ),
    ]
