# Generated by Django 4.2.6 on 2025-03-05 17:35

from django.db import migrations, models
import proyecto_ips_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_ips_app', '0002_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=10, validators=[proyecto_ips_app.models.validar_telefono], verbose_name='Número de telefono'),
        ),
    ]
