# Generated by Django 4.2.6 on 2025-03-05 21:14

import django.core.validators
from django.db import migrations, models
import proyecto_ips_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_ips_app', '0003_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo debe contener letras y espacios', regex='^[A-Za-z\\s]+$')], verbose_name='Ciudad de residencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento no es válido', regex='^\\d{6,10}')], verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator(message='Correo electrónico inválido')], verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('V', 'Viudo/a'), ('UL', 'Union libre'), ('D', 'Divorciado/a')], max_length=20, verbose_name='Estado civil       '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo debe contener letras y espacios', regex='^[A-Za-z\\s]+$'), django.core.validators.MinLengthValidator(3)], verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=proyecto_ips_app.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Imagen de Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo debe contener letras y espacios', regex='^[A-Za-z\\s]+$'), django.core.validators.MinLengthValidator(5)], verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='La contraseña debe tener mínimo 4 caracteres, una mayúscula, un número y un carácter especial', regex='^(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{4,}$')], verbose_name='Contraseña'),
        ),
    ]
