# Generated by Django 5.1.6 on 2025-03-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_ips_app', '0003_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('V', 'Viudo/a'), ('UL', 'Union libre'), ('D', 'Divorciado/a')], max_length=20, verbose_name='Estado civil       '),
        ),
    ]
