# Generated by Django 4.2.6 on 2025-03-12 19:23

import datetime
import django.core.validators
from django.db import migrations, models
import proyecto_ips_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_ips_app', '0004_alter_usuario_ciudad_alter_usuario_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(max_length=100, validators=[proyecto_ips_app.models.validar_caracter], verbose_name='Ciudad de residencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('V', 'Viudo/a'), ('UL', 'Union libre'), ('D', 'Divorciado/a')], max_length=20, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=100, validators=[proyecto_ips_app.models.validar_caracter, django.core.validators.MinLengthValidator(3, message='El campo debe contener minimo 3 caracteres')], verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(max_length=100, validators=[proyecto_ips_app.models.validar_caracter, django.core.validators.MinLengthValidator(5, message='El campo debe contener minimo 5 caracteres')], verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=10, unique=True, validators=[proyecto_ips_app.models.validar_telefono], verbose_name='Número de telefono'),
        ),
    ]
